project_identifier_env: 'CROWDIN_PROJECT_ID'
api_key_env: 'CROWDIN_API_KEY'

base_url: https://api.crowdin.com
base_path: ./game

files:
  -
    source: '/locale/en-PT/**/*.po'
    translation: /locale/%locale%/LC_MESSAGES/%original_file_name%
